#!/bin/bash

g++ -std=c++11 -o example example.cpp
g++ -std=c++11 -o computationalComplexity computationalComplexity.cpp
./example
echo ""
./computationalComplexity
./chartAscending
./chartDescending




